FAIL src/word-search.spec.js   word search     ○ skipped should find all the words in the sample puzzle     createPuzzle       ✓ should be a list of cells with value and coordinates (4ms)     candidatesFor       ✕ should produce candidates starting from all cells with the words first char (4ms)       ✕ should produce candidates of the right length       ✕ should produce candidates in all directions (5ms)
  ● word search › candidatesFor › should produce candidates starting from all cells with the words first char

    TypeError: Cannot read property 'value' of undefined

       5 |       .map((char, x) => ({ value: char, x, y }) ))
       6 |
    >  7 | const toValue = cell => cell.value
         |                              ^
       8 | const toCoords = cell => `(${cell.x},${cell.y})`
       9 |
      10 | const createCandidate = cells => ({

      at map (src/word-search.js:7:30)
          at Array.map (<anonymous>)
      at createCandidate (src/word-search.js:11:15)
      at look (src/word-search.js:33:12)
      at map (src/word-search.js:37:62)
          at Array.map (<anonymous>)
      at flatMap (src/word-search.js:37:45)
          at Array.flatMap (<anonymous>)
      at candidatesFor (src/word-search.js:37:17)
      at Object.it (src/word-search.spec.js:59:26)

  ● word search › candidatesFor › should produce candidates of the right length

    TypeError: Cannot read property 'value' of undefined

       5 |       .map((char, x) => ({ value: char, x, y }) ))
       6 |
    >  7 | const toValue = cell => cell.value
         |                              ^
       8 | const toCoords = cell => `(${cell.x},${cell.y})`
       9 |
      10 | const createCandidate = cells => ({

      at map (src/word-search.js:7:30)
          at Array.map (<anonymous>)
      at createCandidate (src/word-search.js:11:15)
      at look (src/word-search.js:33:12)
      at map (src/word-search.js:37:62)
          at Array.map (<anonymous>)
      at flatMap (src/word-search.js:37:45)
          at Array.flatMap (<anonymous>)
      at candidatesFor (src/word-search.js:37:17)
      at Object.it (src/word-search.spec.js:66:21)

  ● word search › candidatesFor › should produce candidates in all directions

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Array [
        "c1",
        "c2",
        "c3",
    -   "c4",
        "c5",
    -   "c6",
    -   "c7",
    -   "c8",
      ]

      75 |       `))
      76 |       const words = candidatesFor(puzzle, 'cx').map(c => c.word)
    > 77 |       expect(words).toEqual([ 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8' ])
         |                     ^
      78 |     })
      79 |   })
      80 |

      at Object.it (src/word-search.spec.js:77:21)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 1 skipped, 1 passed, 5 total
Snapshots:   0 total
Time:        1.743s
Ran all test suites.