FAIL src/word-search.spec.js   word search     ○ skipped should find all the words in the sample puzzle     createPuzzle       ✓ should be a list of cells with value and coordinates (5ms)     candidatesFor       ✕ should find candidates starting at all cells with value matching word start (5ms)       ✕ should find candidates the right length       ✕ should find candidates in all directions (5ms)
  ● word search › candidatesFor › should find candidates starting at all cells with value matching word start

    TypeError: Cannot read property 'value' of undefined

       7 | const createCandidate = cells => {
       8 |   return {
    >  9 |     word: cells.map(c => c.value).join(''),
         |                            ^
      10 |     path: cells.map(c => `(${c.x},${c.y})`).join(',')
      11 |   }
      12 | }

      at map (src/word-search.js:9:28)
          at Array.map (<anonymous>)
      at createCandidate (src/word-search.js:9:17)
      at map (src/word-search.js:28:12)
          at Array.map (<anonymous>)
      at flatMap (src/word-search.js:32:49)
          at Array.flatMap (<anonymous>)
      at candidatesFor (src/word-search.js:32:21)
      at Object.it (src/word-search.spec.js:59:14)

  ● word search › candidatesFor › should find candidates the right length

    TypeError: Cannot read property 'value' of undefined

       7 | const createCandidate = cells => {
       8 |   return {
    >  9 |     word: cells.map(c => c.value).join(''),
         |                            ^
      10 |     path: cells.map(c => `(${c.x},${c.y})`).join(',')
      11 |   }
      12 | }

      at map (src/word-search.js:9:28)
          at Array.map (<anonymous>)
      at createCandidate (src/word-search.js:9:17)
      at map (src/word-search.js:28:12)
          at Array.map (<anonymous>)
      at flatMap (src/word-search.js:32:49)
          at Array.flatMap (<anonymous>)
      at candidatesFor (src/word-search.js:32:21)
      at Object.it (src/word-search.spec.js:67:21)

  ● word search › candidatesFor › should find candidates in all directions

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Array [
        "c1",
    -   "c2",
    -   "c3",
    -   "c4",
        "c5",
    -   "c6",
    -   "c7",
    -   "c8",
      ]

      76 |       `))
      77 |       const words = candidatesFor(puzzle, 'cx').map(c => c.word)
    > 78 |       expect(words).toEqual([
         |                     ^
      79 |         'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8'
      80 |       ])
      81 |

      at Object.it (src/word-search.spec.js:78:21)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 1 skipped, 1 passed, 5 total
Snapshots:   0 total
Time:        1.067s
Ran all test suites.